"""Storyboard-aware analyzer.

Eats a Chinese short-drama storyboard table (镜号 / 画面描述 / 台词 / 景别 /
人物 / 备注 / 时长) and returns a structured BGM plan:

{
    "title": str,
    "total_duration_s": int,
    "primary_tone": str,
    "primary_intensity": int,
    "shots": [
        {
            "id": int, "start_s": int, "end_s": int, "duration_s": int,
            "narrative_func": [str, ...],   # e.g. ["反转", "结果"]
            "shot_scale": str,              # 景别
            "shot_movement": str,           # 运镜
            "tone": str,                    # one of ALLOWED_TONES
            "intensity": int,               # 1-10
            "dialogue_zh": str,
            "summary_zh": str
        }, ...
    ],
    "cues": [
        {
            "id": int, "start_s": int, "end_s": int,
            "tone": str, "intensity_peak": int,
            "shot_ids": [int, ...],
            "narrative_summary": str,
            "transition_in": str,           # cold | swell | hit | drop
            "transition_out": str
        }, ...
    ]
}

Design notes:
- We do this in ONE GPT call (storyboard → shots + cues) so the model can
  decide cue boundaries with full context, not by post-hoc clustering.
- Tone vocabulary covers short-drama tropes (羞辱/反击/豪门/静默/异常)
  in addition to the 7 film-score tones. See tone_params.TONE_PARAMS.
- We deliberately tell GPT to ignore SFX cues for music-generation purposes:
  SFX is generated by the video model, not by BGM.
"""
from __future__ import annotations
import json
import re
from typing import Optional

from .config import Config
from .http_util import SESSION
from .tone_params import TONE_PARAMS

ALLOWED_TONES = list(TONE_PARAMS.keys())

SYSTEM_PROMPT = (
    "你是一位资深短剧 BGM 音乐总监，熟悉抖音/快手/掌阅短剧的节奏与情绪设计。"
    "你会读分镜表，按镜头粒度判断情绪，然后聚合成 3-6 段可演奏的音乐 cue。"
    "你不负责音效（SFX 由视频模型处理），只负责底色 BGM。"
    "你只输出 JSON，不输出任何解释。"
)


def _build_prompt(storyboard_text: str, title: str) -> str:
    return f"""分析以下短剧分镜表，输出 BGM 规划 JSON。

剧本标题: {title}

分镜表：
{storyboard_text[:8000]}

【任务一】把每个镜头转成 shots[]，提取这些字段（每镜一条）：
  - id: 镜号（整数）
  - start_s, end_s, duration_s: 时间范围（整数秒）
  - narrative_func: 列表，从画面描述/备注里抽出叙事功能标签
    （钩子/冲突/反应/信息/转折/反转/铺垫/关键动作/紧迫感/异常/结果/决定 等）
  - shot_scale: 景别（特写/近景/中近景/中景/广角/低角度/俯拍 等，原文照抄）
  - shot_movement: 运镜（固定/推近/跟拍/摇镜/下摇/手部特写组接 等，原文照抄）
  - tone: 该镜的情绪基调，**严格**从 {ALLOWED_TONES} 里选一个最贴近的
  - intensity: 1-10 整数，该镜的情绪强度峰值
  - dialogue_zh: 中文台词原文（无台词写空字符串）
  - summary_zh: 一句中文场景概括

【任务二】把 shots 聚合成 cues[]（音乐段落，3-6 段）：
  - cue 是连续的、音乐性格相对统一的时间段
  - **强制切 cue 的边界**：
    1) 出现"反转/关键动作/异常"功能的镜头边界
    2) 相邻镜头 intensity 差 ≥ 3
    3) 相邻镜头 tone 跨基调类（如紧张↔静默、冲突↔反击）
  - 每段 cue 至少 6 秒，最长 30 秒
  - 输出字段：
    - id, start_s, end_s
    - tone: 该 cue 的主基调，从 {ALLOWED_TONES}
    - intensity_peak: 该 cue 的强度峰值（取该段镜头里最大的 intensity）
    - shot_ids: 该 cue 覆盖的镜号列表
    - narrative_summary: 一句中文，描述这段在剧情上做什么
    - transition_in: 进入方式（cold / swell / hit / drop）
    - transition_out: 退出方式

【任务三】总体字段：
  - total_duration_s: 整片总时长（用 shots 最后一条的 end_s）
  - primary_tone: 全片主基调，取累计时长最大的 cue tone
  - primary_intensity: 全片主强度，取所有 cue 的 intensity_peak 最大值

【硬性规则】
- 严禁把 SFX 备注（如金属震颤、电流爆闪、暴雨雷鸣、尖叫）当作要生成的内容。
  SFX 视频模型已经处理，BGM 只决定底色氛围。
- tone 必须是允许列表里的中文词，不允许自创。
- cues 的 start_s/end_s 必须无缝衔接，第一个从 0 开始，最后一个等于 total_duration_s。
- 只输出 JSON 对象，schema:
{{
  "title": "{title}",
  "total_duration_s": int,
  "primary_tone": str,
  "primary_intensity": int,
  "shots": [...],
  "cues": [...]
}}
"""


def analyze_storyboard(
    storyboard_text: str,
    title: str,
    config: Optional[Config] = None,
) -> dict:
    """Call GPT to parse the storyboard into shots[] + cues[]."""
    cfg = config or Config()
    payload = {
        "model": cfg.gpt_model,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": _build_prompt(storyboard_text, title)},
        ],
        "temperature": 0.4,
        "response_format": {"type": "json_object"},
    }
    headers = {
        "Authorization": f"Bearer {cfg.gpt_api_key}",
        "Content-Type": "application/json",
    }
    r = SESSION.post(
        f"{cfg.gpt_api_base}/chat/completions",
        headers=headers, json=payload, timeout=120,
    )
    r.raise_for_status()
    content = r.json()["choices"][0]["message"]["content"]
    data = json.loads(content)
    return _sanitize(data, title, storyboard_text)


# ---------- post-processing & guard rails ----------

def _sanitize(data: dict, title: str, storyboard_text: str) -> dict:
    """Coerce GPT output into the strict shape we promise downstream."""
    data["title"] = title

    shots = data.get("shots") or []
    for s in shots:
        s["id"] = int(s.get("id", 0))
        s["start_s"] = int(s.get("start_s", 0))
        s["end_s"] = int(s.get("end_s", s["start_s"]))
        s["duration_s"] = max(1, s["end_s"] - s["start_s"])
        s["tone"] = _coerce_tone(s.get("tone"))
        s["intensity"] = _coerce_intensity(s.get("intensity"))
        s["narrative_func"] = s.get("narrative_func") or []
        s.setdefault("shot_scale", "")
        s.setdefault("shot_movement", "")
        s.setdefault("dialogue_zh", "")
        s.setdefault("summary_zh", "")

    if shots:
        data["total_duration_s"] = int(data.get("total_duration_s") or shots[-1]["end_s"])
    else:
        data["total_duration_s"] = int(data.get("total_duration_s") or _fallback_duration(storyboard_text))

    cues = data.get("cues") or []
    cues = _repair_cue_continuity(cues, data["total_duration_s"])
    for i, c in enumerate(cues):
        c["id"] = i + 1
        c["tone"] = _coerce_tone(c.get("tone"))
        c["intensity_peak"] = _coerce_intensity(c.get("intensity_peak"))
        c.setdefault("shot_ids", [])
        c.setdefault("narrative_summary", "")
        c.setdefault("transition_in", "swell")
        c.setdefault("transition_out", "swell")
    data["cues"] = cues

    data["primary_tone"] = _coerce_tone(data.get("primary_tone")) if data.get("primary_tone") else _infer_primary_tone(cues)
    data["primary_intensity"] = _coerce_intensity(
        data.get("primary_intensity") or max((c["intensity_peak"] for c in cues), default=5)
    )
    return data


def _coerce_tone(tone) -> str:
    if isinstance(tone, str) and tone in ALLOWED_TONES:
        return tone
    if isinstance(tone, str):
        # tolerate "羞辱/对峙" → "羞辱"
        head = tone.split("/")[0].strip()
        if head in ALLOWED_TONES:
            return head
    return "紧张"


def _coerce_intensity(v) -> int:
    try:
        x = int(v)
    except (TypeError, ValueError):
        return 5
    return max(1, min(10, x))


def _repair_cue_continuity(cues: list, total: int) -> list:
    """Make cues a seamless cover of [0, total]. Drops zero-length cues."""
    if not cues:
        return [{
            "id": 1, "start_s": 0, "end_s": total,
            "tone": "紧张", "intensity_peak": 5,
            "shot_ids": [], "narrative_summary": "",
            "transition_in": "cold", "transition_out": "swell",
        }]
    cues = sorted(cues, key=lambda c: int(c.get("start_s", 0)))
    fixed = []
    cursor = 0
    for c in cues:
        s = int(c.get("start_s", cursor))
        e = int(c.get("end_s", s))
        if e <= s:
            continue
        if s < cursor:
            s = cursor
        if s > cursor and fixed:
            fixed[-1]["end_s"] = s
        c2 = dict(c)
        c2["start_s"] = s
        c2["end_s"] = e
        fixed.append(c2)
        cursor = e
    if fixed:
        fixed[0]["start_s"] = 0
        fixed[-1]["end_s"] = total
    return fixed


def _infer_primary_tone(cues: list) -> str:
    tone_dur: dict[str, int] = {}
    for c in cues:
        t = _coerce_tone(c.get("tone"))
        tone_dur[t] = tone_dur.get(t, 0) + max(0, int(c.get("end_s", 0)) - int(c.get("start_s", 0)))
    return max(tone_dur.items(), key=lambda kv: kv[1])[0] if tone_dur else "紧张"


def _fallback_duration(text: str) -> int:
    matches = re.findall(r"(\d+)\s*-\s*(\d+)\s*s", text)
    if not matches:
        return 80
    return max(int(end) for _, end in matches)
